import { createHmac } from "node:crypto";
import { test, expect } from "@playwright/test";
import { createClient } from "@supabase/supabase-js";

const supabaseUrl=process.env.SUPABASE_TEST_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;
const anonKey=process.env.SUPABASE_TEST_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const serviceKey=process.env.SUPABASE_TEST_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;
const password="ASAR-E2E-Password-42!";
if(!supabaseUrl||!anonKey||!serviceKey) throw new Error("Supabase E2E environment is required");
const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
const anon=createClient(supabaseUrl,anonKey,{auth:{persistSession:false,autoRefreshToken:false}});
const state={};

const unique=(name)=>`asar-e2e-${name}-${Date.now()}-${Math.random().toString(16).slice(2)}@example.test`;
async function makeUser(name){const email=unique(name);const {data,error}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:`ASAR ${name}`,preferred_language:"ru",accepted_terms_version:"2026-08-08",accepted_privacy_version:"2026-08-08",age_confirmed_18:true}});if(error)throw error;return{id:data.user.id,email};}
async function browserSignIn(page,email){await page.goto("/ru/auth/sign-in");await page.locator('input[name="email"]').fill(email);await page.locator('input[name="password"]').fill(password);await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/\/ru\/dashboard/);}
async function onboard(page,role){const r=await page.request.post("/api/onboarding/complete",{data:{role}});expect(r.ok()).toBeTruthy();}
async function createRequest(page,title="Помощь с продуктами"){const [{data:cat},{data:city}]=await Promise.all([admin.from("categories").select("id").limit(1).single(),admin.from("cities").select("id,name_ru").eq("is_active",true).limit(1).single()]);const r=await page.request.post("/api/requests",{data:{title,description:"Нужна безопасная помощь с доставкой продуктов домой, без срочной угрозы.",content_language:"ru",category_id:cat.id,city:city.name_ru,district:"Центр",city_id:city.id,district_id:null,address:"Тестовый адрес 10",location_notes:"У подъезда",desired_date:null,time_from:null,time_to:null,urgency:"normal",help_format:"delivery",image_url:null,special_conditions:null,preferred_contact_method:"phone",contact_value:"+77000000000",volunteer_instructions:"Позвонить после выбора",reward_type:"thanks",reward_note:"Спасибо",status:"open",safety_consent:true}});expect(r.ok()).toBeTruthy();return (await r.json()).id;}
async function directSignIn(email){const c=createClient(supabaseUrl,anonKey,{auth:{persistSession:false,autoRefreshToken:false}});const {error}=await c.auth.signInWithPassword({email,password});if(error)throw error;return c;}
function b32(s){const a="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="",out=[];for(const ch of s.replace(/=+$/,"")){const v=a.indexOf(ch.toUpperCase());if(v>=0)bits+=v.toString(2).padStart(5,"0");}for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out)}
function otp(secret){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac("sha1",b32(secret)).update(b).digest();const o=h[h.length-1]&15;return String((h.readUInt32BE(o)&0x7fffffff)%1e6).padStart(6,"0")}

test.describe.serial("ASAR 1.0 core production flow",()=>{
 test.beforeAll(async()=>{state.b=await makeUser("B");state.c=await makeUser("C");state.m=await makeUser("Admin");await admin.from("profiles").update({role:"admin",can_request:true,can_volunteer:true,status:"active"}).eq("id",state.m.id)});
 test.afterAll(async()=>{for(const key of ["a","b","c","m"])if(state[key]?.id)await admin.auth.admin.deleteUser(state[key].id).catch(()=>undefined)});

 test("1 signup -> onboarding -> requester creates request",async({page})=>{const email=unique("A");await page.goto("/ru/auth/sign-up");await page.locator('input[name="full_name"]').fill("ASAR User A");await page.locator('input[name="email"]').fill(email);await page.locator('input[name="password"]').fill(password);for(const n of ["age_consent","accept_terms","accept_privacy"])await page.locator(`input[name="${n}"]`).check();await page.locator('button[type="submit"]').click();await expect(page).toHaveURL(/\/ru\/onboarding/);const {data:list}=await admin.auth.admin.listUsers();state.a=list.users.find(u=>u.email===email);state.a.email=email;await onboard(page,"requester");state.request=await createRequest(page);const {data:r}=await admin.from("help_requests").select("status").eq("id",state.request).single();expect(r.status).toBe("open")});

 test("2 volunteer catalog -> request -> response",async({page})=>{await page.setViewportSize({width:320,height:800});await browserSignIn(page,state.b.email);await onboard(page,"volunteer");await page.goto("/ru/requests");expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await expect(page.locator(`a[href="/ru/requests/${state.request}"]`).first()).toBeVisible();await page.goto(`/ru/requests/${state.request}`);await expect(page.getByText("Тестовый адрес 10")).toHaveCount(0);const response=await page.request.post(`/api/requests/${state.request}/responses`,{data:{message:"Готов помочь с доставкой в согласованное время."}});expect(response.ok()).toBeTruthy();const {data:row}=await admin.from("responses").select("id").eq("request_id",state.request).eq("volunteer_id",state.b.id).single();state.response=row.id});

 test("3 requester selects volunteer",async({page})=>{await browserSignIn(page,state.a.email);const r=await page.request.post(`/api/responses/${state.response}/select`,{data:{}});expect(r.ok()).toBeTruthy();const {data:a}=await admin.from("assignments").select("id,status").eq("request_id",state.request).single();state.assignment=a.id;expect(a.status).toBe("volunteer_selected")});

 test("4 selected volunteer sees private details -> starts -> completes",async({page})=>{await browserSignIn(page,state.b.email);await page.goto(`/ru/assignments/${state.assignment}`);await expect(page.getByText("Тестовый адрес 10")).toBeVisible();let r=await page.request.post(`/api/assignments/${state.assignment}/transition`,{data:{action:"start"}});expect(r.ok()).toBeTruthy();r=await page.request.post(`/api/assignments/${state.assignment}/transition`,{data:{action:"mark_done",help_minutes:45}});expect(r.ok()).toBeTruthy();const {data:a}=await admin.from("assignments").select("status,help_minutes").eq("id",state.assignment).single();expect(a).toMatchObject({status:"awaiting_confirmation",help_minutes:45})});

 test("5 requester confirms -> review -> reputation updates once",async({page})=>{await browserSignIn(page,state.a.email);let r=await page.request.post(`/api/assignments/${state.assignment}/transition`,{data:{action:"confirm"}});expect(r.ok()).toBeTruthy();r=await page.request.post(`/api/assignments/${state.assignment}/reviews`,{data:{rating:5,text:"Спасибо за помощь"}});expect(r.ok()).toBeTruthy();const {data:vp}=await admin.from("volunteer_profiles").select("successful_helps_count,positive_reviews_count,reputation_points").eq("user_id",state.b.id).single();expect(vp.successful_helps_count).toBeGreaterThanOrEqual(1);expect(vp.positive_reviews_count).toBeGreaterThanOrEqual(1);const duplicate=await page.request.post(`/api/assignments/${state.assignment}/reviews`,{data:{rating:5,text:"Дубль"}});expect(duplicate.ok()).toBeFalsy()});

 test("6 volunteer withdraws pending response",async({page})=>{await browserSignIn(page,state.a.email);const request=await createRequest(page,"Перенести коробки");state.withdrawRequest=request;await browserSignIn(page,state.b.email);let r=await page.request.post(`/api/requests/${request}/responses`,{data:{message:"Могу помочь перенести коробки после обеда."}});expect(r.ok()).toBeTruthy();const {data:resp}=await admin.from("responses").select("id").eq("request_id",request).eq("volunteer_id",state.b.id).single();r=await page.request.post(`/api/responses/${resp.id}/withdraw`,{data:{}});expect(r.ok()).toBeTruthy();const {data:after}=await admin.from("responses").select("status").eq("id",resp.id).single();expect(after.status).toBe("withdrawn")});

 test("7 volunteer cancels assignment and requester reassigns",async({page})=>{await browserSignIn(page,state.a.email);const request=await createRequest(page,"Забрать лекарства");state.reassignRequest=request;await browserSignIn(page,state.b.email);await page.request.post(`/api/requests/${request}/responses`,{data:{message:"Могу забрать и привезти лекарства."}});let {data:resp}=await admin.from("responses").select("id").eq("request_id",request).eq("volunteer_id",state.b.id).single();await browserSignIn(page,state.a.email);let r=await page.request.post(`/api/responses/${resp.id}/select`,{data:{}});expect(r.ok()).toBeTruthy();let {data:ass}=await admin.from("assignments").select("id").eq("request_id",request).eq("status","volunteer_selected").single();await browserSignIn(page,state.b.email);r=await page.request.post(`/api/assignments/${ass.id}/transition`,{data:{action:"cancel",reason:"Изменились обстоятельства"}});expect(r.ok()).toBeTruthy();await browserSignIn(page,state.c.email);await onboard(page,"volunteer");await page.request.post(`/api/requests/${request}/responses`,{data:{message:"Готов помочь вместо первого волонтёра."}});({data:resp}=await admin.from("responses").select("id").eq("request_id",request).eq("volunteer_id",state.c.id).single());await browserSignIn(page,state.a.email);r=await page.request.post(`/api/responses/${resp.id}/select`,{data:{}});expect(r.ok()).toBeTruthy();({data:ass}=await admin.from("assignments").select("id,volunteer_id").eq("request_id",request).neq("status","cancelled").single());state.reassignedAssignment=ass.id;expect(ass.volunteer_id).toBe(state.c.id);const b=await directSignIn(state.b.email);const {data:privateData}=await b.from("request_private_details").select("address").eq("request_id",request);expect(privateData).toHaveLength(0)});

 test("8 participant opens a dispute",async({page})=>{await browserSignIn(page,state.c.email);const r=await page.request.post(`/api/assignments/${state.reassignedAssignment}/transition`,{data:{action:"dispute",reason:"requester_unresponsive",description:"Не удаётся связаться с requester после назначения."}});expect(r.ok()).toBeTruthy();const {data:d}=await admin.from("disputes").select("id,status").eq("assignment_id",state.reassignedAssignment).single();state.dispute=d.id;expect(d.status).toBe("open")});

 test("9 privacy controls hide public profile but preserve participant-safe identity",async({page})=>{await browserSignIn(page,state.c.email);const r=await page.request.patch("/api/profile",{data:{full_name:"ASAR C",city:"Астана",district:"Центр",show_public_name:false,show_city:false,share_community_activity:false,allow_public_profile:false,transactional_email_enabled:true,marketing_email_enabled:false}});expect(r.ok()).toBeTruthy();const {data:publicRows}=await anon.from("public_profiles").select("id").eq("id",state.c.id);expect(publicRows).toHaveLength(0);const a=await directSignIn(state.a.email);const {data:participant}=await a.rpc("get_response_participant_profiles");expect(participant.some(x=>x.volunteer_id===state.c.id)).toBeTruthy()});

 test("10 admin MFA gates moderation and resolved dispute is audited",async({page})=>{await browserSignIn(page,state.m.email);await page.goto("/ru/admin");await expect(page).toHaveURL(/\/ru\/admin\/mfa/);const m=await directSignIn(state.m.email);const {data:e,error}=await m.auth.mfa.enroll({factorType:"totp",friendlyName:"ASAR E2E"});if(error)throw error;const {error:v}=await m.auth.mfa.challengeAndVerify({factorId:e.id,code:otp(e.totp.secret)});if(v)throw v;const {error:resolve}=await m.rpc("admin_resolve_dispute",{p_dispute_id:state.dispute,p_action:"reopen_request",p_reason:"E2E moderation decision"});expect(resolve).toBeNull();const {data:audit}=await admin.from("moderation_actions").select("action_type,reason").eq("target_id",state.dispute).order("created_at",{ascending:false}).limit(1).single();expect(audit.action_type).toContain("dispute")});
});
