import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Bell } from "lucide-react";
import { MarkNotificationsRead } from "@/components/notification-actions";
import { Badge, buttonStyles } from "@/components/ui/primitives";
import { EmptyState, ErrorState } from "@/components/ui/states";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale}=await params;const safe:Locale=isLocale(locale)?locale:"ru";return{title:getDictionary(safe).notifications.title,robots:{index:false,follow:false}}}
export default async function NotificationsPage({params}:{params:Promise<{locale:string}>}){const {locale:raw}=await params;const locale:Locale=isLocale(raw)?raw:"ru";const d=getDictionary(locale);const supabase=await createSupabaseServerClient();if(!supabase)return <section className="section"><div className="shell"><ErrorState title={d.states.notConfigured}/></div></section>;const {data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/${locale}/auth/sign-in?next=/${locale}/notifications`);const {data,error}=await supabase.from('notifications').select('id,type,title_key,body_key,link,read_at,created_at').eq('user_id',auth.user.id).order('created_at',{ascending:false}).limit(100);if(error)return <section className="section"><div className="shell"><ErrorState title={d.states.error}/></div></section>;const items=data??[];return <section className="section"><div className="shell max-w-4xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">ASAR</p><h1 className="section-title">{d.notifications.title}</h1></div>{items.some(item=>!item.read_at)?<MarkNotificationsRead dictionary={d}/>:null}</div>{items.length?<div className="mt-8 grid gap-3">{items.map(item=>{const rawKey=item.title_key.replace(/^notifications\./,'');const key=rawKey as keyof typeof d.notifications;const title=typeof d.notifications[key]==='string'?String(d.notifications[key]):item.type;return <article className={`content-card ${item.read_at?'opacity-75':''}`} key={item.id}><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><Bell className="mt-1 text-[var(--brand)]"/><div><div className="flex flex-wrap items-center gap-2"><strong>{title}</strong>{!item.read_at?<Badge tone="brand">{d.notifications.unread}</Badge>:null}</div><time className="mt-1 block text-sm text-[var(--muted)]" dateTime={item.created_at}>{new Intl.DateTimeFormat(locale==='ru'?'ru-RU':'kk-KZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.created_at))}</time></div></div><div className="flex gap-2">{item.link?<Link className={buttonStyles('secondary')} href={item.link.startsWith('/')?`/${locale}${item.link.replace(/^\/(ru|kk)/,'')}`:`/${locale}/dashboard`}>{d.common.open}</Link>:null}{!item.read_at?<MarkNotificationsRead id={item.id} dictionary={d}/>:null}</div></div></article>})}</div>:<div className="mt-8"><EmptyState title={d.notifications.empty}/></div>}</div></section>}
