import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AdminNav } from "@/components/admin-nav";
import { RequestImageRemoveForm, UserBlockForm, VerificationResolveForm } from "@/components/admin-actions";
import { Badge, Rating, UserAvatar, buttonStyles } from "@/components/ui/primitives";
import { EmptyState, ErrorState } from "@/components/ui/states";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { localizedAdminAction, localizedRole, localizedStatus, localizedVerificationKind } from "@/lib/admin-labels";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;const safe:Locale=isLocale(locale)?locale:"ru";return{title:getDictionary(safe).admin.userDetail,robots:{index:false,follow:false}}}
export default async function AdminUserDetailPage({params}:{params:Promise<{locale:string;id:string}>}){
 const{locale:raw,id}=await params;const locale:Locale=isLocale(raw)?raw:"ru";const d=getDictionary(locale);const supabase=await createSupabaseServerClient();if(!supabase)return <section className="section"><div className="shell"><ErrorState title={d.states.notConfigured}/></div></section>;const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/${locale}/auth/sign-in?next=/${locale}/admin/users/${id}`);const{data:me}=await supabase.from('profiles').select('role').eq('id',auth.user.id).maybeSingle();if(me?.role!=="admin")return <section className="section"><div className="shell"><ErrorState title={d.admin.accessDenied}/></div></section>;const{data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel!=="aal2")redirect(`/${locale}/admin/mfa`);
 const [profileResult,volunteerResult,requestsResult,responsesResult,reviewsResult,reportsResult,auditResult,bonusResult,verificationResult]=await Promise.all([
  supabase.from('profiles').select('id,full_name,email,avatar_url,role,status,rating,completed_tasks_count,trust_score,trust_level,reputation_points,reputation_level,email_verified,phone_verified,identity_verified,community_verified,can_request,can_volunteer,created_at,last_active_at').eq('id',id).maybeSingle(),
  supabase.from('volunteer_profiles').select('verification_status,level,bio,skills,availability,positive_reviews_count,successful_helps_count,last_active_at').eq('user_id',id).maybeSingle(),
  supabase.from('help_requests').select('id,title,status,created_at,selected_volunteer_id,image_url').eq('author_id',id).order('created_at',{ascending:false}).limit(50),
  supabase.from('responses').select('id,request_id,message,status,created_at').eq('volunteer_id',id).order('created_at',{ascending:false}).limit(50),
  supabase.from('reviews').select('id,assignment_id,rating,text,author_id,receiver_id,created_at').or(`author_id.eq.${id},receiver_id.eq.${id}`).order('created_at',{ascending:false}).limit(50),
  supabase.from('reports').select('id,target_type,target_id,reason,description,status,author_id,created_at,resolution_note').or(`author_id.eq.${id},target_id.eq.${id}`).order('created_at',{ascending:false}).limit(50),
  supabase.from('moderation_actions').select('id,admin_id,action_type,reason,previous_value,new_value,created_at,target_type,target_id').eq('target_user_id',id).order('created_at',{ascending:false}).limit(50),
  supabase.from('bonus_transactions').select('id,amount,reason,note,created_at').eq('volunteer_id',id).order('created_at',{ascending:false}).limit(50),
  supabase.from('verification_requests').select('id,kind,status,note,review_reason,created_at,reviewed_at').eq('user_id',id).order('created_at',{ascending:false}).limit(20),
 ]);
 const profile=profileResult.data;const volunteer=volunteerResult.data;if(!profile)return <section className="section"><div className="shell"><ErrorState title={d.profile.notFound}/></div></section>;const requestIds=(requestsResult.data??[]).map(r=>r.id);const [asVolunteer,asRequester]=await Promise.all([supabase.from('assignments').select('id,request_id,volunteer_id,status,help_minutes,created_at,cancellation_reason').eq('volunteer_id',id).order('created_at',{ascending:false}).limit(50),requestIds.length?supabase.from('assignments').select('id,request_id,volunteer_id,status,help_minutes,created_at,cancellation_reason').in('request_id',requestIds).order('created_at',{ascending:false}).limit(50):Promise.resolve({data:[] as never[],error:null})]);const assignments=[...(asVolunteer.data??[]),...(asRequester.data??[])].filter((item,index,all)=>all.findIndex(other=>other.id===item.id)===index);
 const cards=[[d.admin.requests,requestsResult.data?.length??0],[d.dashboard.responses,responsesResult.data?.length??0],[d.dashboard.active,assignments.length],[d.dashboard.reviews,reviewsResult.data?.length??0],[d.admin.reports,reportsResult.data?.length??0],[d.admin.audit,auditResult.data?.length??0]];
 return <section className="section"><div className="shell"><AdminNav locale={locale} dictionary={d}/><div className="content-card mt-8"><div className="flex flex-wrap items-start justify-between gap-6"><div className="flex items-center gap-4"><UserAvatar name={profile.full_name} src={profile.avatar_url} size="lg"/><div><h1 className="text-3xl font-extrabold">{profile.full_name}</h1><p className="text-[var(--muted)]">{profile.email??'—'}</p><div className="mt-2 flex flex-wrap gap-2"><Badge tone={profile.status==='blocked'?'danger':'success'}>{localizedStatus(profile.status,d)}</Badge><Badge>{localizedRole(profile.role,d)}</Badge></div></div></div><div className="w-full max-w-sm"><UserBlockForm userId={id} blocked={profile.status==='blocked'} dictionary={d}/></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><small className="text-[var(--muted)]">{d.admin.trust}</small><strong className="block text-2xl">{profile.trust_score}</strong></div><div><small className="text-[var(--muted)]">{d.dashboard.reputation}</small><strong className="block text-2xl">{profile.reputation_points}</strong></div><div><small className="text-[var(--muted)]">{d.dashboard.rating}</small><Rating value={profile.rating}/></div><div><small className="text-[var(--muted)]">{d.admin.completedHelp}</small><strong className="block text-2xl">{volunteer?.successful_helps_count ?? profile.completed_tasks_count}</strong><span className="text-xs text-[var(--muted)]">{localizedStatus(volunteer?.verification_status,d)}</span></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{cards.map(([label,value])=><div className="content-card" key={String(label)}><strong className="text-2xl">{value}</strong><span className="block text-sm text-[var(--muted)]">{label}</span></div>)}</div>
 <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="content-card"><h2 className="text-2xl font-extrabold">{d.admin.verification}</h2><div className="mt-4 grid gap-4">{verificationResult.data?.length?verificationResult.data.map(v=><article className="rounded-2xl border border-[var(--line)] p-4" key={v.id}><div className="flex justify-between gap-3"><strong>{localizedVerificationKind(v.kind,d)}</strong><Badge>{localizedStatus(v.status,d)}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">{v.note??'—'}</p>{v.status==='pending'?<div className="mt-4"><VerificationResolveForm requestId={v.id} dictionary={d}/></div>:v.review_reason?<p className="mt-3 text-sm">{v.review_reason}</p>:null}</article>):<EmptyState title={d.states.empty}/>}</div></section><section className="content-card"><h2 className="text-2xl font-extrabold">{d.admin.audit}</h2><div className="mt-4 grid gap-3">{auditResult.data?.length?auditResult.data.map(a=><article className="rounded-2xl border border-[var(--line)] p-4" key={a.id}><div className="flex justify-between gap-3"><strong>{localizedAdminAction(a.action_type,d)}</strong><time className="text-sm text-[var(--muted)]">{new Intl.DateTimeFormat(locale==='ru'?'ru-RU':'kk-KZ').format(new Date(a.created_at))}</time></div><p className="mt-2 text-sm">{a.reason}</p></article>):<EmptyState title={d.states.empty}/>}</div></section></div>
 <section className="content-card mt-6 overflow-x-auto"><h2 className="text-2xl font-extrabold">{d.admin.requests}</h2>{requestsResult.data?.length?<table className="data-table mt-4"><thead><tr><th>{d.createRequest.requestTitle}</th><th>{d.admin.status}</th><th>{d.admin.registrationDate}</th><th/></tr></thead><tbody>{requestsResult.data.map(r=><tr key={r.id}><td>{r.title}</td><td>{localizedStatus(r.status,d)}</td><td>{new Intl.DateTimeFormat(locale==='ru'?'ru-RU':'kk-KZ').format(new Date(r.created_at))}</td><td><div className="grid gap-2">{r.status==='open'?<Link className={buttonStyles('ghost')} href={`/${locale}/requests/${r.id}`}>{d.common.open}</Link>:null}{r.image_url?<RequestImageRemoveForm requestId={r.id} dictionary={d}/>:null}</div></td></tr>)}</tbody></table>:<EmptyState title={d.states.empty}/>}</section>
 <section className="content-card mt-6 overflow-x-auto"><h2 className="text-2xl font-extrabold">{d.dashboard.active}</h2>{assignments.length?<table className="data-table mt-4"><thead><tr><th>ID</th><th>{d.admin.status}</th><th>{d.assignment.duration}</th><th>{d.assignment.cancelReason}</th></tr></thead><tbody>{assignments.map(a=><tr key={a.id}><td><code>{a.id.slice(0,8)}</code></td><td>{localizedStatus(a.status,d)}</td><td>{a.help_minutes??0}</td><td>{a.cancellation_reason??'—'}</td></tr>)}</tbody></table>:<EmptyState title={d.states.empty}/>}</section>
 <section className="content-card mt-6 overflow-x-auto"><h2 className="text-2xl font-extrabold">{d.admin.reports}</h2>{reportsResult.data?.length?<table className="data-table mt-4"><thead><tr><th>{d.admin.status}</th><th>{d.requestDetail.reportReason}</th><th>{d.createRequest.description}</th></tr></thead><tbody>{reportsResult.data.map(r=><tr key={r.id}><td>{localizedStatus(r.status,d)}</td><td>{r.reason}</td><td>{r.description??'—'}</td></tr>)}</tbody></table>:<EmptyState title={d.states.empty}/>}</section>
 <section className="content-card mt-6"><h2 className="text-2xl font-extrabold">{d.bonus.title}</h2><p className="mt-2 text-[var(--muted)]">{d.bonus.subtitle}</p>{bonusResult.data?.length?<div className="mt-4 grid gap-2">{bonusResult.data.map(b=><div className="flex justify-between rounded-xl border border-[var(--line)] p-3" key={b.id}><span>{b.reason}</span><strong>{b.amount>0?'+':''}{b.amount}</strong></div>)}</div>:null}</section>
 </div></section>
}
