import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { AdminNav } from "@/components/admin-nav";
import { Badge } from "@/components/ui/primitives";
import { EmptyState, ErrorState } from "@/components/ui/states";
import { getDictionary,isLocale,type Locale } from "@/lib/i18n";
import { localizedAdminAction, localizedAdminTarget } from "@/lib/admin-labels";
import { createSupabaseServerClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const{locale}=await params;const safe:Locale=isLocale(locale)?locale:"ru";return{title:getDictionary(safe).admin.audit,robots:{index:false,follow:false}}}
export default async function AuditPage({params}:{params:Promise<{locale:string}>}){const{locale:raw}=await params;const locale:Locale=isLocale(raw)?raw:"ru";const d=getDictionary(locale);const supabase=await createSupabaseServerClient();if(!supabase)return <section className="section"><div className="shell"><ErrorState title={d.states.notConfigured}/></div></section>;const{data:auth}=await supabase.auth.getUser();if(!auth.user)redirect(`/${locale}/auth/sign-in?next=/${locale}/admin/audit`);const{data:me}=await supabase.from('profiles').select('role').eq('id',auth.user.id).maybeSingle();if(me?.role!=="admin")return <section className="section"><div className="shell"><ErrorState title={d.admin.accessDenied}/></div></section>;const{data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel!=="aal2")redirect(`/${locale}/admin/mfa`);const{data}=await supabase.from('moderation_actions').select('id,admin_id,target_user_id,target_type,target_id,action_type,reason,previous_value,new_value,created_at').order('created_at',{ascending:false}).limit(200);const ids=[...new Set((data??[]).flatMap(x=>[x.admin_id,x.target_user_id].filter(Boolean) as string[]))];const{data:profiles}=ids.length?await supabase.from('profiles').select('id,full_name').in('id',ids):{data:[]};const names=new Map((profiles??[]).map(p=>[p.id,p.full_name]));return <section className="section"><div className="shell"><AdminNav locale={locale} dictionary={d}/><p className="section-kicker mt-8">{d.admin.management}</p><h1 className="section-title">{d.admin.audit}</h1>{data?.length?<div className="content-card mt-8 overflow-x-auto"><table className="data-table"><thead><tr><th>{d.admin.registrationDate}</th><th>{d.admin.administrator}</th><th>{d.admin.action}</th><th>{d.admin.target}</th><th>{d.admin.reason}</th><th>{d.admin.previous}</th><th>{d.admin.newValue}</th></tr></thead><tbody>{data.map(a=><tr key={a.id}><td>{new Intl.DateTimeFormat(locale==='ru'?'ru-RU':'kk-KZ',{dateStyle:'short',timeStyle:'short'}).format(new Date(a.created_at))}</td><td>{names.get(a.admin_id)??a.admin_id.slice(0,8)}</td><td><Badge>{localizedAdminAction(a.action_type,d)}</Badge></td><td>{a.target_user_id?names.get(a.target_user_id)??a.target_user_id.slice(0,8):localizedAdminTarget(a.target_type,d)}</td><td>{a.reason}</td><td><code className="text-xs">{a.previous_value?JSON.stringify(a.previous_value):'—'}</code></td><td><code className="text-xs">{a.new_value?JSON.stringify(a.new_value):'—'}</code></td></tr>)}</tbody></table></div>:<div className="mt-8"><EmptyState title={d.states.empty}/></div>}</div></section>}
