import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, CheckCircle2, HeartHandshake, LockKeyhole, ShieldCheck, Star, UsersRound } from "lucide-react";
import { CategoryIcon } from "@/components/category-icon";
import { ProductAnalyticsEvent } from "@/components/product-analytics";
import { CommunityEventCard } from "@/components/community/community-event-card";
import { CommunityImpact } from "@/components/community/community-impact";
import { Badge, buttonStyles } from "@/components/ui/primitives";
import { EmptyState } from "@/components/ui/states";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { getCommunitySnapshot } from "@/services/community";
import { getCategories } from "@/services/requests";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const safe: Locale = isLocale(locale) ? locale : "ru"; const d = getDictionary(safe); return { title: d.nav.home, description: d.home.subtitle }; }

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale: Locale = isLocale(raw) ? raw : "ru"; const dictionary = getDictionary(locale);
  const [categoriesResult, community] = await Promise.all([getCategories(), getCommunitySnapshot(3)]); const categories = categoriesResult.data.slice(0, 8);
  return <>
    <ProductAnalyticsEvent event="landing_visit" locale={locale} />
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="section-kicker">{dictionary.home.eyebrow}</p><h1>{dictionary.home.title}</h1><p>{dictionary.home.subtitle}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/${locale}/requests/new`} className={buttonStyles("primary")}>{dictionary.home.getHelp}<ArrowRight size={20} /></Link><Link href={`/${locale}/auth/sign-up`} className={buttonStyles("secondary")}>{dictionary.home.becomeVolunteer}</Link></div><span className="trust-pill"><ShieldCheck size={19} />{dictionary.home.trustNote}</span></div><div className="hero-visual" aria-hidden="true"><span className="hero-orbit" /><span className="hero-core"><HeartHandshake /></span><div className="floating-card floating-card-one"><span><UsersRound /></span><strong>{dictionary.home.communityCard}</strong></div><div className="floating-card floating-card-two"><span><BadgeCheck /></span><strong>{dictionary.trust.title}</strong></div><div className="floating-card floating-card-three"><span><CheckCircle2 /></span><strong>{dictionary.home.helpCompleted}</strong></div></div></div></section>

    <section className="section impact-home"><div className="shell"><div className="section-heading-row"><div><p className="section-kicker">{dictionary.impact.eyebrow}</p><h2 className="section-title">{dictionary.impact.title}</h2><p className="section-lead">{dictionary.impact.subtitle}</p></div><Badge tone={community.configured ? "success" : "neutral"}>{community.configured ? dictionary.impact.liveData : dictionary.impact.waitingData}</Badge></div><div className="mt-9"><CommunityImpact metrics={community.impact} dictionary={dictionary} /></div></div></section>

    <section className="section bg-[var(--surface-soft)]"><div className="shell"><p className="section-kicker">01 · {dictionary.home.howTitle}</p><h2 className="section-title">{dictionary.home.howTitle}</h2><p className="section-lead">{dictionary.home.howSubtitle}</p><div className="steps-grid mt-10">{dictionary.home.steps.map((item, index) => <article className="step-card" key={item.title}><span className="step-number">{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>

    <section className="section trust-section"><div className="shell trust-section-grid"><div><p className="section-kicker">02 · {dictionary.home.trustSectionTitle}</p><h2 className="section-title">{dictionary.home.trustSectionTitle}</h2><p className="section-lead">{dictionary.home.trustSectionText}</p><ul className="trust-list">{dictionary.home.trustItems.map((item) => <li key={item}><CheckCircle2 />{item}</li>)}</ul><Link href={`/${locale}/about#safety`} className={buttonStyles("secondary")}>{dictionary.home.safetyMore}<ArrowRight /></Link></div><div className="trust-demo-card"><span className="trust-demo-shield"><ShieldCheck /></span><div><small>{dictionary.trust.score}</small></div><h3>{dictionary.trust.forming}</h3><p>{dictionary.trust.subtitle}</p><div className="demo-verifications"><span><BadgeCheck />{dictionary.trust.email}</span><span><BadgeCheck />{dictionary.trust.phone}</span><span><LockKeyhole />{dictionary.home.addressProtected}</span></div></div></div></section>

    <section className="section bg-[var(--secondary)]"><div className="shell"><div className="section-heading-row"><div><p className="section-kicker">03 · {dictionary.requests.category}</p><h2 className="section-title">{dictionary.home.categoriesTitle}</h2><p className="section-lead">{dictionary.home.categoriesSubtitle}</p></div><Link href={`/${locale}/requests`} className={buttonStyles("secondary")}>{dictionary.nav.requests}<ArrowRight /></Link></div><div className="mt-8">{categories.length ? <div className="category-grid">{categories.map((category) => { const title = locale === "ru" ? category.name_ru : category.name_kk; const description = locale === "ru" ? category.description_ru : category.description_kk; return <Link href={`/${locale}/requests?category=${category.slug}`} className="category-card" key={category.id}><span className="category-icon"><CategoryIcon name={category.icon} /></span><h3>{title}</h3><p>{description}</p></Link>; })}</div> : <EmptyState title={categoriesResult.configured ? dictionary.states.empty : dictionary.states.notConfigured} />}</div></div></section>

    <section className="section community-preview"><div className="shell"><div className="section-heading-row"><div><p className="section-kicker">05 · {dictionary.community.eyebrow}</p><h2 className="section-title">{dictionary.community.feedTitle}</h2><p className="section-lead">{dictionary.community.feedText}</p></div><Link href={`/${locale}/community`} className={buttonStyles("secondary")}>{dictionary.community.openCommunity}<ArrowRight /></Link></div>{community.events.length ? <div className="community-feed community-feed-preview mt-9">{community.events.map((event) => <CommunityEventCard key={event.id} event={event} locale={locale} dictionary={dictionary} />)}</div> : <div className="mt-9"><EmptyState variant="community" title={dictionary.community.emptyTitle} text={dictionary.community.emptyText} /></div>}</div></section>

    <section className="section"><div className="shell"><p className="section-kicker">06 · {dictionary.home.advantagesTitle}</p><h2 className="section-title">{dictionary.home.advantagesTitle}</h2><div className="feature-grid mt-10">{[LockKeyhole, ShieldCheck, Star].map((FeatureIcon, index) => { const item = dictionary.home.advantages[index]; return <article className="feature-card" key={item.title}><span className="category-icon"><FeatureIcon /></span><h3>{item.title}</h3><p>{item.text}</p></article>; })}</div></div></section>

    <section className="section faq-preview"><div className="narrow"><p className="section-kicker">07 · FAQ</p><h2 className="section-title">{dictionary.faq.title}</h2><div className="faq-list mt-9">{dictionary.faq.items.slice(0, 5).map((item) => <details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div><Link href={`/${locale}/faq`} className={`${buttonStyles("secondary")} mt-7`}>{dictionary.common.learnMore}<ArrowRight /></Link></div></section>

    <section className="section pt-0"><div className="shell final-cta"><HeartHandshake /><h2>{dictionary.home.ctaTitle}</h2><p>{dictionary.home.ctaText}</p><div><Link href={`/${locale}/requests/new`} className={buttonStyles("secondary")}>{dictionary.home.getHelp}</Link><Link href={`/${locale}/requests`} className="cta-link">{dictionary.home.becomeVolunteer}<ArrowRight /></Link></div></div></section>
  </>;
}
