import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { BarChart3, FolderKanban, ShieldAlert, UsersRound } from "lucide-react";
import Link from "next/link";
import { ReportResolveForm } from "@/components/admin-actions";
import { AdminNav } from "@/components/admin-nav";
import { buttonStyles } from "@/components/ui/primitives";
import { Badge } from "@/components/ui/primitives";
import { EmptyState, ErrorState } from "@/components/ui/states";
import { CommunityImpact } from "@/components/community/community-impact";
import { getCommunitySnapshot } from "@/services/community";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const safe: Locale = isLocale(locale) ? locale : "ru"; return { title: getDictionary(safe).nav.admin }; }
export default async function AdminPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale: Locale = isLocale(raw) ? raw : "ru"; const dictionary = getDictionary(locale); const supabase = await createSupabaseServerClient();
  if (!supabase) return <section className="section"><div className="shell"><ErrorState title={dictionary.states.notConfigured} /></div></section>;
  const { data: auth } = await supabase.auth.getUser(); if (!auth.user) redirect(`/${locale}/auth/sign-in?next=/${locale}/admin`);
  const { data: profile } = await supabase.from("profiles").select("role").eq("id", auth.user.id).maybeSingle(); if (profile?.role !== "admin") return <section className="section"><div className="shell"><ErrorState title={dictionary.admin.accessDenied} /></div></section>;const{data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();if(aal?.currentLevel!=="aal2")redirect(`/${locale}/admin/mfa`);
  const [reports, users, requests, categories, verification, audit, achievements, events, impact, disputes] = await Promise.all([supabase.from("reports").select("id,target_type,target_id,reason,description,status,created_at").order("created_at", { ascending: false }).limit(50), supabase.from("profiles").select("id", { count: "exact", head: true }), supabase.from("help_requests").select("id", { count: "exact", head: true }), supabase.from("categories").select("id", { count: "exact", head: true }), supabase.from("volunteer_profiles").select("user_id", { count: "exact", head: true }).eq("verification_status", "pending"), supabase.from("moderation_actions").select("id", { count: "exact", head: true }), supabase.from("achievements").select("id", { count: "exact", head: true }), supabase.from("community_events").select("id", { count: "exact", head: true }).eq("is_published", true), getCommunitySnapshot(1), supabase.from("disputes").select("id", { count: "exact", head: true }).in("status", ["open","reviewing"])]);
  const stats = [[dictionary.admin.users, users.count ?? 0, UsersRound], [dictionary.admin.requests, requests.count ?? 0, FolderKanban], [dictionary.admin.reports, reports.data?.length ?? 0, ShieldAlert], [dictionary.admin.categories, categories.count ?? 0, BarChart3]] as const;
  const management = [[dictionary.admin.verification, verification.count ?? 0], [dictionary.admin.trustFlags, audit.count ?? 0], [dictionary.admin.communityEvents, events.count ?? 0], [dictionary.admin.achievements, achievements.count ?? 0], [dictionary.admin.categories, categories.count ?? 0], [dictionary.admin.disputes, disputes.count ?? 0]] as const;
  return <section className="section"><div className="shell"><AdminNav locale={locale} dictionary={dictionary} /><p className="section-kicker mt-8">{dictionary.admin.eyebrow}</p><h1 className="section-title">{dictionary.admin.title}</h1><p className="section-lead">{dictionary.admin.subtitle}</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{stats.map(([label, value, Icon]) => <div className="content-card" key={label}><Icon className="text-[var(--brand)]" /><strong className="mt-4 block text-3xl">{value}</strong><span className="text-[var(--muted)]">{label}</span></div>)}</div><section className="mt-8 content-card"><h2 className="text-2xl font-extrabold">{dictionary.impact.title}</h2><div className="mt-6"><CommunityImpact metrics={impact.impact} dictionary={dictionary} /></div></section><section className="mt-8"><h2 className="text-2xl font-extrabold">{dictionary.admin.management}</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{management.map(([label,value]) => <article className="content-card" key={label}><span className="section-kicker">{dictionary.admin.status}</span><strong className="mt-2 block text-3xl">{value}</strong><span className="text-[var(--muted)]">{label}</span></article>)}</div></section><div className="mt-6 flex flex-wrap gap-3"><Link className={buttonStyles("secondary")} href={`/${locale}/admin/users`}>{dictionary.admin.users}</Link><Link className={buttonStyles("secondary")} href={`/${locale}/admin/disputes`}>{dictionary.admin.openDisputes}</Link><Link className={buttonStyles("secondary")} href={`/${locale}/admin/audit`}>{dictionary.admin.audit}</Link></div><div className="mt-8 content-card overflow-x-auto"><h2 className="mb-5 text-2xl font-extrabold">{dictionary.admin.reports}</h2>{reports.data?.length ? <table className="data-table"><thead><tr><th>{dictionary.admin.status}</th><th>{dictionary.admin.action}</th><th>{dictionary.createRequest.description}</th><th /></tr></thead><tbody>{reports.data.map((report) => <tr key={report.id}><td><Badge tone={report.status === "resolved" ? "success" : "warning"}>{report.status}</Badge></td><td>{report.reason}<small className="block text-[var(--muted)]">{report.target_type}</small></td><td>{report.description ?? "—"}</td><td>{report.status !== "resolved" ? <ReportResolveForm reportId={report.id} dictionary={dictionary} /> : null}</td></tr>)}</tbody></table> : <EmptyState variant="activity" title={dictionary.admin.noReports} text={dictionary.admin.noReportsText} />}</div></div></section>;
}
