import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { Award, CheckCircle2, ClipboardList, MessageSquareText, Plus, Star } from "lucide-react";
import { SignOutButton } from "@/components/auth-form";
import { CancelRequestButton, ReopenRequestButton, ReviewForm, SelectVolunteerButton, WithdrawResponseButton } from "@/components/dashboard-actions";
import { EnableVolunteerButton } from "@/components/capability-button";
import { AccountControls } from "@/components/account-controls";
import { DashboardSidebar } from "@/components/dashboard-sidebar";
import { ProfileForm } from "@/components/profile-form";
import { Badge, Rating, StatusBadge, UserAvatar, buttonStyles } from "@/components/ui/primitives";
import { EmptyState, ErrorState } from "@/components/ui/states";
import { TrustCard } from "@/components/trust/trust-card";
import { VerificationRequest } from "@/components/verification-request";
import { ReputationCard } from "@/components/reputation/reputation-card";
import { AchievementCard } from "@/components/achievements/achievement-card";
import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getDashboardData } from "@/services/dashboard";
import { getLocations } from "@/services/locations";
import type { RequestStatus, ResponseStatus } from "@/types/domain";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; const safe: Locale = isLocale(locale) ? locale : "ru"; return { title: getDictionary(safe).nav.dashboard }; }

export default async function DashboardPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale: Locale = isLocale(raw) ? raw : "ru"; const dictionary = getDictionary(locale); const supabase = await createSupabaseServerClient();
  if (!supabase) return <section className="section"><div className="shell"><ErrorState title={dictionary.states.notConfigured} text={dictionary.auth.notConfigured} /></div></section>;
  const { data: auth } = await supabase.auth.getUser(); if (!auth.user) redirect(`/${locale}/auth/sign-in?next=/${locale}/dashboard`);
  const [data, locations] = await Promise.all([getDashboardData(auth.user.id), getLocations()]); if (!data?.profile) return <section className="section"><div className="shell"><ErrorState title={dictionary.states.error} text={dictionary.states.unauthorized} /></div></section>;
  const profile = data.profile;
  if (!profile.onboarding_completed_at || !profile.role) redirect(`/${locale}/onboarding`);
  const role = profile.role;
  const requestById = new Map(data.requests.map((item) => [item.id, item]));
  const activeAssignments = data.assignments.filter((item) => item.status !== "completed" && item.status !== "cancelled");
  return (
    <section className="section"><div className="shell">
      <div className="flex flex-wrap items-end justify-between gap-5"><div className="flex items-center gap-4"><UserAvatar name={profile.full_name} src={profile.avatar_url} size="lg" /><div><p className="section-kicker">{dictionary.dashboard.eyebrow}</p><h1 className="font-[Georgia] text-4xl font-bold md:text-5xl">{dictionary.dashboard.hello}, {profile.full_name}</h1></div></div><div className="flex gap-3">{profile.can_request ? <Link className={buttonStyles("primary")} href={`/${locale}/requests/new`}><Plus size={19} />{dictionary.dashboard.newRequest}</Link> : null}<SignOutButton locale={locale} label={dictionary.nav.signOut} /></div></div>
      <div className="mt-10 grid gap-7 lg:grid-cols-[240px_1fr]"><DashboardSidebar locale={locale} dictionary={dictionary} role={role} canRequest={Boolean(profile.can_request)} canVolunteer={Boolean(profile.can_volunteer)} /><div className="grid gap-8">
        <div className="grid gap-4 sm:grid-cols-3"><div className="content-card"><Star className="text-[var(--sun)]" /><strong className="mt-4 block text-3xl">{profile.rating.toFixed(1)}</strong><span className="text-sm text-[var(--muted)]">{dictionary.dashboard.rating}</span></div><div className="content-card"><CheckCircle2 className="text-[var(--brand)]" /><strong className="mt-4 block text-3xl">{profile.completed_tasks_count}</strong><span className="text-sm text-[var(--muted)]">{dictionary.dashboard.completedTasks}</span></div><div className="content-card"><Award className="text-[var(--sun)]" /><strong className="mt-4 block text-3xl">{profile.reputation_points ?? 0}</strong><span className="text-sm text-[var(--muted)]">{dictionary.dashboard.reputation}</span></div></div>
        {!profile.can_volunteer ? <div><EnableVolunteerButton dictionary={dictionary} /></div> : null}<section id="trust"><TrustCard profile={profile} dictionary={dictionary} locale={locale} /></section>
        <section className="content-card" id="verification"><h2 className="text-2xl font-extrabold">{dictionary.verification.title}</h2><p className="mt-2 text-[var(--muted)]">{dictionary.verification.description}</p><div className="mt-5"><VerificationRequest dictionary={dictionary} pending={data.verificationRequests.some((item) => item.status === "pending")} /></div>{data.verificationRequests.length ? <div className="mt-5 grid gap-2">{data.verificationRequests.slice(0, 3).map((item) => <div className="rounded-2xl border border-[var(--line)] p-3" key={item.id}><strong>{item.kind === "identity" ? dictionary.verification.identity : dictionary.verification.community}</strong><span className="ml-2 text-sm text-[var(--muted)]">{dictionary.verification.status[item.status as keyof typeof dictionary.verification.status] ?? item.status}</span>{item.review_reason ? <p className="mt-2 text-sm text-[var(--muted)]">{item.review_reason}</p> : null}</div>)}</div> : null}</section>
        <section id="rating"><ReputationCard profile={profile} dictionary={dictionary} /></section>
        <section className="content-card" id="achievements"><div className="section-heading-row"><div><p className="section-kicker">{dictionary.achievements.eyebrow}</p><h2 className="text-3xl font-extrabold">{dictionary.achievements.title}</h2></div><Award className="text-[var(--accent)]" /></div><div className="achievement-grid mt-7">{data.achievements.slice(0, 6).map((achievement) => { const progress = data.achievementProgress.find((item) => item.achievement_id === achievement.id); return <AchievementCard key={achievement.id} dictionary={dictionary} achievement={{ id: achievement.id, name: locale === "ru" ? achievement.name_ru : achievement.name_kk, description: locale === "ru" ? achievement.description_ru : achievement.description_kk, rarity: achievement.rarity, progress: progress?.progress ?? 0, target: progress?.target ?? Math.max(1, achievement.required_completed_tasks), unlocked_at: progress?.unlocked_at ?? null }} />; })}</div></section>
        <section className="content-card" id="profile"><h2 className="text-2xl font-extrabold">{dictionary.dashboard.profile}</h2><p className="mt-2 text-[var(--muted)]">{dictionary.profile.privateNote}</p><div className="mt-6"><ProfileForm profile={profile} volunteer={profile.can_volunteer ? data.volunteer : null} dictionary={dictionary} locale={locale} cities={locations.cities} districts={locations.districts} /></div></section><section className="content-card" id="account"><h2 className="text-2xl font-extrabold">{dictionary.account.title}</h2><div className="mt-5"><AccountControls dictionary={dictionary} locale={locale} /></div></section>
        {profile.can_request || profile.role === "admin" ? <section className="content-card" id="requests"><div className="flex items-center justify-between"><h2 className="text-2xl font-extrabold">{dictionary.dashboard.myRequests}</h2><ClipboardList className="text-[var(--brand)]" /></div>{data.requests.length ? <div className="mt-5 grid gap-3">{data.requests.map((item) => <article className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[var(--line)] p-4" key={item.id}><Link href={`/${locale}/requests/${item.id}`} className="font-extrabold hover:text-[var(--brand)]">{item.title}</Link><div className="flex flex-wrap items-center gap-2"><StatusBadge status={item.status as RequestStatus} dictionary={dictionary} />{item.status === "draft" || item.status === "open" ? <Link className={buttonStyles("ghost")} href={`/${locale}/requests/${item.id}/edit`}>{dictionary.dashboard.editRequest}</Link> : null}{!["completed","cancelled"].includes(item.status) ? <CancelRequestButton requestId={item.id} dictionary={dictionary} /> : null}{item.status === "cancelled" ? <ReopenRequestButton requestId={item.id} dictionary={dictionary} /> : null}</div></article>)}</div> : <div className="mt-5"><EmptyState title={dictionary.states.empty} text={dictionary.requests.emptyText} /></div>}</section> : null}
        <section className="content-card" id="responses"><div className="flex items-center justify-between"><h2 className="text-2xl font-extrabold">{dictionary.dashboard.responses}</h2><MessageSquareText className="text-[var(--brand)]" /></div>{data.responses.length ? <div className="mt-5 grid gap-4">{data.responses.map((response) => <article className="rounded-2xl border border-[var(--line)] p-4" key={response.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{response.request_title ?? requestById.get(response.request_id)?.title ?? dictionary.dashboard.responses}</strong><small className="mt-1 block text-[var(--muted)]">{response.volunteer_name ?? ""}</small>{response.volunteer_rating !== undefined ? <div><Rating value={response.volunteer_rating} /></div> : null}</div><StatusBadge status={response.status as ResponseStatus} dictionary={dictionary} /></div><p className="mt-3 text-[var(--muted)]">{response.message}</p>{requestById.has(response.request_id) && response.status === "pending" ? <div className="mt-4"><SelectVolunteerButton responseId={response.id} dictionary={dictionary} /></div> : null}{response.volunteer_id === auth.user.id && response.status === "pending" ? <div className="mt-4"><WithdrawResponseButton responseId={response.id} dictionary={dictionary} /></div> : null}</article>)}</div> : <div className="mt-5"><EmptyState title={dictionary.states.empty} /></div>}</section>
        <section className="content-card" id="active"><h2 className="text-2xl font-extrabold">{dictionary.dashboard.active}</h2>{activeAssignments.length ? <div className="mt-5 grid gap-4">{activeAssignments.map((assignment) => <article className="rounded-2xl border border-[var(--line)] p-4" key={assignment.id}><div className="flex flex-wrap items-center justify-between gap-3"><strong>{assignment.request_title}</strong><Badge tone="brand">{dictionary.status[assignment.status as keyof typeof dictionary.status] ?? assignment.status}</Badge></div><div className="mt-4"><Link className={buttonStyles("secondary")} href={`/${locale}/assignments/${assignment.id}`}>{dictionary.dashboard.openAssignment}</Link></div></article>)}</div> : <div className="mt-5"><EmptyState title={dictionary.states.empty} /></div>}</section>
        {data.assignments.filter((item) => item.status === "completed" && item.requester_id === auth.user.id).length ? <section className="content-card" id="reviews"><h2 className="text-2xl font-extrabold">{dictionary.dashboard.reviews}</h2>{data.assignments.filter((item) => item.status === "completed" && item.requester_id === auth.user.id).slice(0, 3).map((assignment) => data.reviews.some((review) => review.assignment_id === assignment.id && review.author_id === auth.user.id) ? <p className="mt-3 text-[var(--muted)]" key={assignment.id}>{dictionary.requestDetail.reviewExists ?? dictionary.states.success}</p> : <ReviewForm key={assignment.id} assignmentId={assignment.id} dictionary={dictionary} />)}</section> : null}
      </div></div>
    </div></section>
  );
}
